name: create_sticker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  cloud_firestore: ^6.6.0
  cupertino_icons: ^1.0.9
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  firebase_storage: ^13.4.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  go_router: ^17.3.0
  http: ^1.6.0
  image_cropper: ^12.2.1
  image_picker: ^1.2.3
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
