// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZjh9v0yqWA8EAJ_IrV-9iqDpVYYMFvU',
    appId: '1:596167366029:web:e13ed8a97635eb33a899c4',
    messagingSenderId: '596167366029',
    projectId: 'stickerhub-a1ce5',
    authDomain: 'stickerhub-a1ce5.firebaseapp.com',
    storageBucket: 'stickerhub-a1ce5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL8tBrbXIaZOi37nZO4Xmu76FUhJPppcQ',
    appId: '1:596167366029:android:8c99356ce74f32a5a899c4',
    messagingSenderId: '596167366029',
    projectId: 'stickerhub-a1ce5',
    storageBucket: 'stickerhub-a1ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhIFXgcfiVTTHUluqOQ10wXgsOKxnW3qU',
    appId: '1:596167366029:ios:6d2a0fb73f3d9f52a899c4',
    messagingSenderId: '596167366029',
    projectId: 'stickerhub-a1ce5',
    storageBucket: 'stickerhub-a1ce5.firebasestorage.app',
    iosBundleId: 'com.example.createSticker',
  );
}
